# File : .pep8speaks.yml

scanner:
    linter: flake8

flake8:
    max-line-length: 100

message:
    opened:
        header: "@{name}, Thanks for opening this PR."
    updated:
        header: "@{name}, Thanks for updating this PR."
