version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=userge
      - POSTGRES_USER=USERNAME
      - POSTGRES_PASSWORD=PASSWORD
    ports:
      - 5432:5432
    restart: always
  userge:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: always
